name: base_repository
description: Abstraction for managing CRUD operations in flutter projects(communication with api).
version: 0.0.1
repository: https://github.com/salihagic/base_repository

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter
  rest_api_client: ^0.0.19
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
